### ISSUE TITLE
Error after end of recording

### ISSUE THREAD

**Issue by vlmendz** [OpenTracksApp/OpenTracks#1373] opened 2022-09-04 13:14 UTC
**Describe the bug**
After the recording is finished, sometimes an error occurs. This error occurred for the first time after updating OpenTracks (see apk version in screenshot).

**To Reproduce**
1. Stop recording 
2. Accept or discard the recording or wait for a while
3. See error (If it occurs)

![20220904_090211.jpg](https://user-images.githubusercontent.com/91810638/188314982-434d0341-b4e7-4044-8489-3a05998e4992.jpg)

**Technical information**
 - See screenshot

**Comment by dennisguse** [comment] 2022-09-04 13:29
Duplicate of #1328.
This problem is already older.
It was kind of alw priority as does not affect the recorded data.

**Closed** 2022-09-04 13:29 UTC
Labels: potential bug
