### ISSUE TITLE
same Bewegungszeit and Gesamtzeit v4.12.2

### ISSUE THREAD

**Issue by Filefabrik** [OpenTracksApp/OpenTracks#1909] opened 2024-05-02 07:37 UTC
**Describe the bug**
"Bewegungszeit" and "Gesamtzeit" are the same values since the update to version 
**To Reproduce**

If applicable:
* add screenshots
* add logcat output

**Technical information**
![tempFileForShare_20240502-093333](https://github.com/OpenTracksApp/OpenTracks/assets/84433563/10e8cbf2-2eaa-417a-a3d8-753aea547ef6)

 - Device: Samsung Tab s2
 - OS: android 10
 - OpenTracks version:  v4.12.2 5470

**Comment by Filefabrik** [comment] 2024-05-02 18:26
In addition: i had have started the recording but forgotten the tablet at home.
...later i was back and i see this screen. 
Hope that helps
![Screenshot_20240502-165302_OpenTracks](https://github.com/OpenTracksApp/OpenTracks/assets/84433563/2df93f64-15ac-439f-8bf6-6478edb565a2)

**Comment by dennisguse** [comment] 2024-05-02 19:14
The first problem: looks like there is something broken. 

The 2nd one is fixed in v4.12.3.

**Comment by Filefabrik** [comment] 2024-05-03 06:46
Okay, thx 
then i will wait until  v4.12.3 is played in fdroid...

**Comment by Grimtown** [comment] 2024-05-03 12:12
Can confirm.

"total time" and "moving time" are the same, no matter how few or many breaks I take.

Nokia XR20
Android 13
OpenTracks v4.12.2

**Comment by dennisguse** [comment] 2024-05-03 18:20
Seems to be a duplicate of #1756. 
And yes something is broken or was never working with the new idle functionality.

**Closed by dennisguse** 2024-05-03 18:20 UTC
Labels: potential bug
