### ISSUE TITLE
Crash on Runtime

### ISSUE THREAD

**Issue by JahidFariz** [OpenTracksApp/OpenTracks#528] opened 2020-11-23 13:00 UTC
Open Tracks v3.13.0 Crash several times repeatedly after I pressed the record button on OPPO F1+ Android Version 5.1

**Comment by dennisguse** [comment] 2020-11-23 15:15
Thanks! 

This is a duplicate of #523.
Fixed in release v3.113.2 (not yet in F-Droid).

**Closed by dennisguse** 2020-11-23 15:15 UTC
