### ISSUE TITLE
Sudden crash after tracing

### ISSUE THREAD

**Issue by ctliang** [OpenTracksApp/OpenTracks#1394] opened 2022-10-13 09:34 UTC
Hi there, 

I just finished  tracing a path and was about to enter a name for it and the app suddenly crashed. It gave me this log and lead me to github.com. 

### App information
* ID: de.dennisguse.opentracks
* Version: 5051 v4.1.1

### Device information
* Brand: volla
* Device: mimameid
* Model: Volla Phone 22
* Id: RQ3A.211001.001
* Product: lineage_mimameid

### Firmware
* SDK: 30
* Release: 11
* Incremental: 101

### Cause of error
```java
Exception in thread "main": java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.services.TrackRecordingServiceNotificationManager.updateContent(java.lang.String)' on a null object reference
	at de.dennisguse.opentracks.services.TrackRecordingService.newGpsStatus(TrackRecordingService.java:270)
	at de.dennisguse.opentracks.services.handlers.TrackPointCreator.sendGpsStatus(TrackPointCreator.java:217)
	at de.dennisguse.opentracks.services.handlers.GPSHandler.onGpsStatusChanged(GPSHandler.java:177)
	at de.dennisguse.opentracks.services.handlers.GpsStatus.sendStatus(GpsStatus.java:210)
	at de.dennisguse.opentracks.services.handlers.GpsStatus.checkStatusFromLastLocation(GpsStatus.java:148)
	at de.dennisguse.opentracks.services.handlers.GpsStatus.onLocationChanged(GpsStatus.java:119)
	at de.dennisguse.opentracks.services.handlers.GpsStatus$GpsStatusRunner.run(GpsStatus.java:52)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by dennisguse** [comment] 2022-10-13 14:14
Sadly a duplicate of #1328.
Some kind of race condition while stopping a recording. 
Luckily no data is lost.

**Closed by dennisguse** 2022-10-13 14:14 UTC
