### ISSUE TITLE
Import of gpx files: calculation of time in motion is wrong

### ISSUE THREAD

**Issue by vlmendz** [OpenTracksApp/OpenTracks#1782] opened 2023-12-09 15:18 UTC
**Describe the bug**

When importing a gpx file created with another application or a version of OT prior to 4.9.x, time in motion = total time

**To Reproduce**
See above 

![Screenshot_20231209_094422_OpenTracks.jpg](https://github.com/OpenTracksApp/OpenTracks/assets/91810638/ccde9ee4-3533-4e66-a4ea-f520d74f6f72)

**Technical information**
 -Device: [Samsung Galaxy A52s 5G]

OS: [One UI 6.0, Android 14]

OpenTracks version: [v4.9.6]

OpenTracks commit id (only for nightly builds): [V4.9.6-1-GF80AAFOOE]

**Comment by dennisguse** [comment] 2023-12-09 15:22
Duplicate of #1770.

**Closed by dennisguse** 2023-12-09 15:22 UTC
Labels: potential bug
