### ISSUE TITLE
OpenTracks randomly crashes after stopping recording

### ISSUE THREAD

**Issue by pitkajuh** [OpenTracksApp/OpenTracks#1784] opened 2023-12-12 14:10 UTC
**Describe the bug**
After stopping recording (I hold stop button), OpenTracks crashes. The crash happens before I have a chance to set the exercise type (walking, running etc.). I did some testing by starting the recording multiple times (with GPS and without GPS). Based on the tests, the crash does not happen every time I stop recording and it seems to be somewhat random.

**To Reproduce**
1. Go to 'Start recording by pressing the big red button (with GPS enabled or disabled)'
2. Click on 'Stop recording button (the orange one)'
3. See error

### App information
* ID: de.dennisguse.opentracks
* Version: 5554 v4.9.6

### Device information
* Brand: google
* Device: bluejay
* Model: Pixel 6a
* Id: UQ1A.231205.015
* Product: bluejay

### Firmware
* SDK: 34
* Release: 14
* Incremental: 2023120800

### Cause of error
```java
Exception in thread "main": java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.sensors.sensorData.AggregatorBarometer.add(de.dennisguse.opentracks.sensors.sensorData.Raw)' on a null object reference
	at de.dennisguse.opentracks.sensors.sensorData.SensorDataSet.update(SensorDataSet.java:123)
	at de.dennisguse.opentracks.sensors.SensorManager$1.onChange(SensorManager.java:38)
	at de.dennisguse.opentracks.sensors.GainManager.onSensorValueChanged(GainManager.java:44)
	at de.dennisguse.opentracks.sensors.driver.BarometerInternal.onSensorChanged(BarometerInternal.java:31)
	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1011)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Technical information**
 - Device: Google Pixel 6a
 - OS: GrapheneOS UQ1A.231205.015
 - OpenTracks version: v4.9.6, 5554

**Comment by dennisguse** [comment] 2023-12-12 17:43
Duplicate of #1779.
I will create a new release now.

Thanks for the repord!

**Closed** 2023-12-12 17:43 UTC
Labels: potential bug
