### ISSUE TITLE
Stat by year / month / week

### ISSUE THREAD

**Issue by DavidHenryThoreau** [OpenTracksApp/OpenTracks#1763] opened 2023-11-16 13:10 UTC
I'm looking at stat button, the stats pops up a calendar to choose between today and the past.
It may be easier to add year / month / week stat and let the button calendar for more precise stat.
Each time I want a stat i've to scroll month (I mean like FitoTrack)
What do you think about it ?

**Comment by dennisguse** [comment] 2024-04-01 09:41
Duplicate of #1872.

**Closed by dennisguse** 2024-04-01 09:41 UTC
Labels: enhancement
