### ISSUE TITLE
PineTime smartwatch support

### ISSUE THREAD

**Issue by aha999** [OpenTracksApp/OpenTracks#1238] opened 2022-05-19 00:17 UTC
**Is your feature request related to a problem? Please describe.**
I couldn't find a way to connect an open source smartwatch [PineTime](https://www.pine64.org/pinetime/) to the OpenTracks app, so the heart rate monitoring would be usable.

**Describe the solution you'd like**
If possible, it would be great if PineTime could be used as a heart BPM monitor with OpenTracks.

**Comment by dennisguse** [comment] 2022-05-19 04:59
This already works.
PineTime doesn't send that it supports heartrate and it's advertisement packets, so the filter (settings -> bluetooth sensors -> only show Bluetooth devices that ann...) must be disabled before searching for the device.
Anyhow, the data is only reported by the PineTime if it's screen is on.
And I found it to be quite imprecise.

Duplicate of #1063 (also more infos).

**Closed by dennisguse** 2022-05-19 04:59 UTC
Labels: enhancement

**Comment by aha999** [comment] 2022-05-19 11:33
Oh, sorry, i didn't find that duplicate because it is spelled together: PineTime, so please edit that title.

**Comment by dennisguse** [comment] 2022-05-19 16:56
Done; no worries.
