### ISSUE TITLE
Can't export or share files by date

### ISSUE THREAD

**Issue by Hob111** [OpenTracksApp/OpenTracks#137] opened 2020-01-30 21:48 UTC
Since the update before last I've been unable to export or share tracks by date name although this is the option chosen in settings. Instead tracks are given consecutive numbers. 
**To Reproduce**
Simply choose export from settings or share from the main screen. 
**Technical information**
 - Device: Motorola Moto E5
 - OS: Android 8.0.0

**Comment by dennisguse** [comment] 2020-01-30 22:05
Is this a duplicate of #130?

**Comment by Hob111** [comment] 2020-01-30 22:09
Yes, sorry, I hadn't checked other bug reports.

**Closed** 2020-01-30 22:37 UTC
Labels: potential bug
