### ISSUE TITLE
Adding custom activity

### ISSUE THREAD

**Issue by fik236** [OpenTracksApp/OpenTracks#1886] opened 2024-04-08 15:12 UTC
**Describe the solution you'd like**
I practise few activities which are not in a list. Is there any possibility how to add new activity?

**Comment by dennisguse** [comment] 2024-04-08 15:28
Yes. 
They are defined in the source code (aka not user configurable).

**Comment by dennisguse** [comment] 2024-04-08 15:40
Duplicate of #1879.

**Closed by dennisguse** 2024-04-08 15:41 UTC
Labels: enhancement
