### ISSUE TITLE
when connected to bluetooth power meter, crashes shortly after pressing start

### ISSUE THREAD

**Issue by telent** [OpenTracksApp/OpenTracks#1833] opened 2024-01-15 21:44 UTC
**Describe the bug**
When connected via bluetooth to my Favero Assioma Uno power meter, the app repeatedly stops shortly after pressing the "start recording" button.

I have only tried this indoors (no gps fix)

**To Reproduce**
1. Connect a power meter
2. Go inside the house
3. Click on "record"
4. Wait 3-4 seconds
5. See error

### App information
* ID: de.dennisguse.opentracks
* Version: 5602 v4.10.0

### Device information
* Brand: OnePlus
* Device: OnePlus6T
* Model: ONEPLUS A6013
* Id: TQ3A.230901.001
* Product: OnePlus6T

### Firmware
* SDK: 33
* Release: 13
* Incremental: eng.root.20231205.195100

### Cause of error
```java
Exception in thread "main": java.lang.ClassCastException:
de.dennisguse.opentracks.sensors.BluetoothHandlerManagerCyclingPower$Data
cannot be cast to de.dennisguse.opentracks.data.models.Power
at
de.dennisguse.opentracks.sensors.sensorData.SensorDataSet.fillTrackPoint(SensorDataSet.java:162)
at de.dennisguse.opentracks.sensors.SensorManager.fill(SensorManager.java:89)
at
de.dennisguse.opentracks.services.handlers.TrackPointCreator.addSensorData(TrackPointCreator.java:64)
at
de.dennisguse.opentracks.services.handlers.TrackPointCreator.onNewTrackPoint(TrackPointCreator.java:85)
at
de.dennisguse.opentracks.services.handlers.TrackPointCreator.onChange(TrackPointCreator.java:80)
at
de.dennisguse.opentracks.sensors.SensorManager$1.onChange(SensorManager.java:39)
at
de.dennisguse.opentracks.sensors.BluetoothHandlerManagerCyclingPower.handlePayload(BluetoothHandlerManagerCyclingPower.java:38)
at
de.dennisguse.opentracks.sensors.BluetoothConnectionManager$1.onCharacteristicChanged(BluetoothConnectionManager.java:130)
at
android.bluetooth.BluetoothGattCallback.onCharacteristicChanged(BluetoothGattCallback.java:159)
at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:525)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7924)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by dennisguse** [comment] 2024-01-15 21:55
Thanks for the report.
And luckily that is already fixed.
You just need to upgrade to v4.10.1

Duplicate of #1802.

PS/ if it is working again you may add the sensor to README_SENSORS.md.
That would be great!

**Closed by dennisguse** 2024-01-15 21:55 UTC
Labels: potential bug
