### ISSUE TITLE
swap date and uuid in export file name so that gpx files are sorted

### ISSUE THREAD

**Issue by pkienzle** [OpenTracksApp/OpenTracks#935] opened 2021-09-02 11:32 UTC
Please swap the track name and uuid so that the files are sorted by trackname rather than uuid.

The following code builds a filename for export:
https://github.com/OpenTracksApp/OpenTracks/blob/017eee8b68c25fd9815c0bcc0b458458f36f50c1/src/main/java/de/dennisguse/opentracks/util/ExportUtils.java#L104

However, UUID appears to be random so gpx files in the export directory look like:
```
{8 hex}_{YYYY-MM-DD hh_mm}.gpx
```
This means I need to scan the entire directory to find the export track for that day.

**Comment by dennisguse** [comment] 2022-05-04 04:51
Duplicate of #512.
Fixed by #1207.

Thanks for the patience...
Change is already in the nightly and will be included in the next result.

**Closed by dennisguse** 2022-05-04 04:51 UTC
