### ISSUE TITLE
[v3.15.0] Voice notification going off every 5 seconds

### ISSUE THREAD

**Issue by jackpoc** [OpenTracksApp/OpenTracks#640] opened 2021-03-09 12:08 UTC
**Describe the bug**
I used opentracks today after updating via F Droid.

The voice notifications were going off every 5 seconds (ish). Was also listening to a podcast using antennapod. There was no way to turn this off. Annoying as it makes OpenTracks unusable for me.

Voice notifications were set for every 5 minutes.

**To Reproduce**
1. Use OpenTracks with headphones
2. Start recording
3. Every 5 seconds get a voice notification of distance update

**Technical information**
 - Device: Nokia 4
 - OS: Android
 - Version: 3.15.3

**Comment by delboy711** [comment] 2021-03-09 18:42
I have the same issue, but only since I upgraded my phone OS from Android 9 (pie) to Android 10 (q)

I have another phone running Android 7 (nougat) and voice notifications work OK

I have tried Opentracks versions 3.5.2/3.5.1/3.5.0 and they all behave the same.

**Comment by dennisguse** [comment] 2021-03-09 18:48
If I remember correctly, there was no recent change in the voice announcement system (at least none that could account for this) - except we moved times from a long to Instant/Duration.

@delboy711 @jackpoc Are you able to compile to check this yourself.
I don't have a test device with TTS at hand (at least not easily).

@delboy711 Thanks for this important detail.

**Comment by rgmf** [comment] 2021-03-09 18:53
@delboy711 @jackpoc I can reproduce the issue but I can turn off the voice from settings. Can you open Settings -> Voice Frequency and set it to Off?

At least you can use OpenTracks until this will be fixed.

**Comment by rgmf** [comment] 2021-03-09 19:17
@dennisguse Fixed and pushed onto main directly.

@jackpoc I hope you can to turn off the voice announcement until new release.

**Comment by jackpoc** [comment] 2021-03-09 20:10
> @dennisguse Fixed and pushed onto main directly.


Thanks for the quick turn around on fixing it!

> @jackpoc I hope you can to turn off the voice announcement until new release

Thanks I have turned it off for now. I didn't notice you could set it to off before for some reason.

**Comment by delboy711** [comment] 2021-03-09 20:44
That was quick!
Thanks for the fix.  I will run with voice notifications switched off until the fix hits f-droid.

**Comment by dennisguse** [comment] 2021-03-09 20:49
Release v3.15.4 contains the fix.
Might hit F-Droid in 2-14 days. ;)

@rgmf Thanks for fixing it.
My fault...

**Comment by rgmf** [comment] 2021-03-10 07:25
> Release v3.15.4 contains the fix.
> Might hit F-Droid in 2-14 days. ;)
> 
> @rgmf Thanks for fixing it.
> My fault...

No problem... I didn't realize of it either. It's a feature I never use because my device don't have TTS :sweat_smile:

**Comment by dennisguse** [comment] 2021-03-10 22:02
@rgmf I also don't have TTS ;)

**Comment by dennisguse** [comment] 2021-03-15 16:40
v3.15.4 is now available via F-Droid.

**Comment by delboy711** [comment] 2021-03-16 12:21
Confirmed v3.15.4 fixes the problem. Thanks

**Comment by jackpoc** [comment] 2021-03-21 20:29
Sorry but it hasn't been fixed for me. Just constant voice notification. I updated the app in f droid.

**Comment by dennisguse** [comment] 2021-03-21 21:50
@jackpoc Can you provide more information on this?

**Comment by jackpoc** [comment] 2021-03-22 11:44
@dennisguse I just realised I only updated to 3.15.2 not v3.15.4. It isn't available yet on F Droid.

**Comment by dennisguse** [comment] 2021-03-22 18:59
@jackpoc Okay ;)
You just need update your local F-Droid repo (pulling down on F-Droid's main screen).

**Closed by dennisguse** 2021-03-22 18:59 UTC
Labels: bug
