### ISSUE TITLE
Feature: Skiing Gear Tracker

### ISSUE THREAD

**Issue by kalo2711** [OpenTracksApp/OpenTracks#1869] opened 2024-02-26 03:12 UTC
Having the right gear for every skiing condition, temperature or tracks is crucial for the most optimal skiing experience, and such a gear tracker would be a great addition to the application. Not only is it beneficial for people that are new to skiing and are still unaware of the right gear to buy for their skiing style, but it also creates opportunities to work with brands to suggest recommendations for different gear.

The gear page will consist of library of skis, boots, poles and fixations with easy to read markers that mention their use case and how well they can be paired with items from other categories on a scale.

An alternative to this feature could be a form that allows for the input of all conditions and factors that create difference in the required skiing gear and give out the necessary gear for the specified conditions.

**Comment by dennisguse** [comment] 2024-02-26 17:59
That sounds pretty out of scope for OpenTracks.
Most likely it is a duplicate of #395.

@kalo2711 if you want to actively work on this, please re-open the issue.

**Closed by dennisguse** 2024-02-26 17:59 UTC
Labels: enhancement
