### ISSUE TITLE
"Bad characters" in file name

### ISSUE THREAD

**Issue by mega-stoffel** [OpenTracksApp/OpenTracks#975] opened 2021-10-08 21:11 UTC
Hej there!
Just today I tried to sync all my tracks to my Windows laptop.
But Windows can't work with colons (:) in the file name, which is used to divide hours:minutes.

Would it be possible to avoid such "bad" characters in file names?

Thanks. :-)

**Comment by dennisguse** [comment] 2021-10-09 08:52
Duplicate of #254.

**Closed by dennisguse** 2021-10-09 08:52 UTC
Labels: enhancement

**Comment by dennisguse** [comment] 2021-10-09 12:21
@mega-stoffel PS/ would you would have some time to look into this that would be awesome!
