### ISSUE TITLE
travelled distance in a month

### ISSUE THREAD

**Issue by PhantomO2** [OpenTracksApp/OpenTracks#474] opened 2020-10-26 05:17 UTC
Please, can you guys add a feature to see, the total distance distance travelled in a month?  Like "Distance travelled in the month of August 2020 :- 80km" or "Total distance travelled in September 2020 is 100 km". This feature will give us an idea of the distance that we have covered in month. We could also add targets. Suppose my target for a month is 100km, then I will know that, I have to cover 20 km more  in the remainig days in the the month of August so as to cover that target. Not just month, you can also do the same thing for weeks too. Like " total distance travelled in the months of August 2020 is 80km" or "The total distance travelled in the first week of August 2020 is 25 km". I used distance travelled instead of running, jogging, walking, cycling because this app gives us the the distance travelled but the end result depends upon the Devs!!! Btw the app is working exceptionally well. Once again thank you for making this world a Lil bit more privacy friendly.

**Comment by dennisguse** [comment] 2020-10-26 17:17
Duplicate of #475 (has a slightly better description).

**Closed by dennisguse** 2020-10-26 17:17 UTC
