### ISSUE TITLE
Crash [updated]

### ISSUE THREAD

**Issue by serrq** [OpenTracksApp/OpenTracks#1881] opened 2024-03-16 11:00 UTC
Android 14
OnePlus CPH2399
Open Tracks 4.12.0

Please give me your support email, then I send you the full report.

![1000108004](https://github.com/OpenTracksApp/OpenTracks/assets/113377431/f75c320a-d3f0-4188-9010-d7205b0a3749)

**Comment by dennisguse** [comment] 2024-03-25 14:17
Duplicate of #1781.

**Closed** 2024-03-25 14:17 UTC
