### ISSUE TITLE
App crash sharing multiple recordings at once

### ISSUE THREAD

**Issue by C-Makridis** [OpenTracksApp/OpenTracks#1721] opened 2023-10-06 23:23 UTC
**Application crashes when hitting the share icon, having selected two tracks**

**To Reproduce**
1. Open OpenTracks
2. long tap on a recorded track to enable multi-select
3. tap on a second track
4. tap on the share icon

accompanying log:

### App information
* ID: de.dennisguse.opentracks
* Version: 5399 v4.8.4

### Device information
* Brand: Ulefone
* Device: Armor_X5_Pro_R
* Model: Armor X5 Pro
* Id: RP1A.200720.011
* Product: Armor_X5_Pro_R_EEA

### Firmware
* SDK: 30
* Release: 11
* Incremental: 1630056088

### Cause of error
```java
Exception in thread "main": java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.ui.TrackListAdapter$ViewHolder.setSelected(boolean)' on a null object reference
	at de.dennisguse.opentracks.ui.TrackListAdapter.setAllSelected(TrackListAdapter.java:135)
	at de.dennisguse.opentracks.ui.TrackListAdapter.onDestroyActionMode(TrackListAdapter.java:126)
	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onDestroyActionMode(AppCompatDelegateImpl.java:3027)
	at androidx.appcompat.view.StandaloneActionMode.finish(StandaloneActionMode.java:110)
	at de.dennisguse.opentracks.ui.TrackListAdapter.onActionItemClicked(TrackListAdapter.java:117)
	at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:3022)
	at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7428)
	at android.view.View.access$3600(View.java:813)
	at android.view.View$PerformClick.run(View.java:28495)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7731)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

Thank you very much for your time and effort.

**Comment by dennisguse** [comment] 2023-10-07 18:34
Duplicate of #1711.

**Closed by dennisguse** 2023-10-07 18:34 UTC
Labels: potential bug
