### ISSUE TITLE
Allow continue recording on a stoped record

### ISSUE THREAD

**Issue by pieplu** [OpenTracksApp/OpenTracks#136] opened 2020-01-30 02:55 UTC
**Is your feature request related to a problem? Please describe.**
Because of issue: #135 and some other reason, your track record can be stop (not paused, stopped), not by your choice

**Describe the solution you'd like**
Allow, on any track record to "continue recording"

**Describe alternatives you've considered**
Allow user to merge 2 tracks record

**Comment by dennisguse** [comment] 2020-01-30 06:14
Duplicate of https://github.com/OpenTracksApp/OpenTracks/issues/11.

**Closed by dennisguse** 2020-01-30 06:14 UTC
Labels: enhancement, good first issue
