### ISSUE TITLE
Idle detection not working when using BLE Speed sensor

### ISSUE THREAD

**Issue by mroethke** [OpenTracksApp/OpenTracks#1894] opened 2024-04-15 12:39 UTC
**Describe the bug**
When I use my BLE Speed Sensor (Wahoo Speed), even when GPS is on, idle detection is not working at all. Every second is counted as moving time, even when the sensor is not measuring anything for several minutes.

**To Reproduce**
1. Start recording
2. don't move and notice how moving time is increasing

**Technical information**
 - Device: FP3
 - OS: LineageOS 20
 - OpenTracks version: v4.12.1 (fdroid)

**Comment by dennisguse** [comment] 2024-04-15 15:01
Duplicate of #1756. 
Sadly, I have little time at the moment.

**Closed by dennisguse** 2024-04-15 15:01 UTC
Labels: potential bug
