### ISSUE TITLE
AggregatorCyclingCadence.add crash

### ISSUE THREAD

**Issue by hercek** [OpenTracksApp/OpenTracks#1814] opened 2024-01-05 10:50 UTC
**Describe the bug**
A crash just after I resumed a tack 

**To Reproduce**
1. Stop recording of a track (with the stop button).
2. Resume the recording (with the play button)
3. A crash within a few seconds.
I do not know whether it is reproducible. Of course, it is not reproducible when I try it at home without cadence data stream. I can try tomorrow with the cadence data available.

**Technical information**
Stack trace and the relevant system info in the attached file.
[OpenTracksCrash1.txt](https://github.com/OpenTracksApp/OpenTracks/files/13841050/OpenTracksCrash1.txt)

**Comment by dennisguse** [comment] 2024-01-05 14:45
This looks like a duplicate of #1799.
It is hopefully fixed due to merging #1810.
If not, please re-open.

**Closed by dennisguse** 2024-01-05 14:45 UTC
Labels: potential bug
