### ISSUE TITLE
wrong Kilometer and Time values (2x)

### ISSUE THREAD

**Issue by mega-stoffel** [OpenTracksApp/OpenTracks#835] opened 2021-06-22 21:47 UTC
**Describe the bug**
recording a track shows wrong values on the "track view" page.
I have twice the kilometers and twice the time of my current workout.

**To Reproduce**
1. start a recording
2. move around for some minutes
3. look at the screen, where all the data of this track is shown
4. You see the double amount of kilometers moved and time spent, as it really was
5. After you stop the recording, the values are correct again.

During recording at 19:28, claiming ~15h, 338km
![Screenshot_20210621-192820](https://user-images.githubusercontent.com/25298441/123003506-922d9680-d3b3-11eb-9973-0e9833a87557.png)
Still recording on the overview of all tracks. It shows, this track was started at 10:54 (about 8,5h earlier, including some breaks)
![Screenshot_20210621-192832](https://user-images.githubusercontent.com/25298441/123003502-90fc6980-d3b3-11eb-8421-a5f8fa10a0d1.png)
After stopping the track, the values were correct again:
![Screenshot_20210621-192842](https://user-images.githubusercontent.com/25298441/123003483-8cd04c00-d3b3-11eb-9445-6560504dbf9a.png)

**Technical information**
 - Device: FP3
 - OS: Android 10
 - Version 3.18.4

Is this maybe the same issue as #828?

**Comment by dennisguse** [comment] 2021-06-23 04:21
Introduced in v3.18.4; 
And yes duplicate of #828.

Recorded data is okay, "just" an UI issue.
Fix is #831; you may compile yourself.
Release is upcoming.


PS: Nice trip!

**Closed by dennisguse** 2021-06-23 04:21 UTC
Labels: potential bug
