### ISSUE TITLE
App 崩溃

### ISSUE THREAD

**Issue by dopdo** [OpenTracksApp/OpenTracks#1988] opened 2024-09-24 09:59 UTC
### App information
* ID: de.dennisguse.opentracks
* Version: 5870 v4.13.1

### Device information
* Brand: Xiaomi
* Device: crux
* Model: Mi9 Pro 5G
* Id: RKQ1.200826.002
* Product: crux

### Firmware
* SDK: 30
* Release: 11
* Incremental: V13.0.1.0.RFXCNXM

### Cause of error
```java
Exception in thread "main": java.lang.RuntimeException: Unable to start activity ComponentInfo{de.dennisguse.opentracks/de.dennisguse.opentracks.ui.markers.MarkerEditActivity}: java.lang.IllegalStateException: TrackId and Location must be provided or an existing markerId
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3540)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalStateException: TrackId and Location must be provided or an existing markerId
	at de.dennisguse.opentracks.ui.markers.MarkerEditActivity.onCreate(MarkerEditActivity.java:101)
	at android.app.Activity.performCreate(Activity.java:8143)
	at android.app.Activity.performCreate(Activity.java:8114)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3513)
	... 11 more
```

**Comment by dennisguse** [comment] 2024-12-19 04:19
Looks like a duplicate of #2030.

**Closed by dennisguse** 2024-12-19 04:19 UTC
Labels: bug
