### ISSUE TITLE
Activity type sort by most used

### ISSUE THREAD

**Issue by danielwerg** [OpenTracksApp/OpenTracks#1952] opened 2024-07-10 12:52 UTC
**Is your feature request related to a problem? Please describe.**
Currently Activity type is always sorted alphabetically.

**Describe the solution you'd like**
Sort Activity type by most used, either add option to settings or/and sorting button next to Activity type

**Describe alternatives you've considered**
1. Clicking Activity type Icon is faster then searching in input box.
2. Selecting Default activity type in settings (Not ideal if you do more than 1 activity regularly, also there no list unless you start typing #1953)

**Additional context**

Also, sort of related, would be nice to have "Clear" (`X`) button for Activity type

![Screenshot](https://github.com/OpenTracksApp/OpenTracks/assets/35052399/475093ab-d949-4998-ba64-d72779668c7d)

**Comment by dennisguse** [comment] 2024-07-11 04:26
Duplicate of #1331.

**Closed by dennisguse** 2024-07-11 04:26 UTC
Labels: enhancement
