### ISSUE TITLE
Unable to stop activity when using gestures system navigation

### ISSUE THREAD

**Issue by JanezCZ** [OpenTracksApp/OpenTracks#1971] opened 2024-08-16 05:09 UTC
**Describe the bug**
When Android system is set to gestures navigation and help is hidden, it is almost impossible to stop the activity.
It seems like system is taking long press as start of a gesture and therefore does not forward press to an app.

**To Reproduce**
1. Set system to gestures navigation
2. Hide navigation hint
3. Start activity
4. Try to hold stop button

**Technical information**
 - Device: Fairphone 3
 - OS: /e/OS 2.2-t-20240715417772-stable-FP3
 - OpenTracks version: 4.13.0 (code 5837)

**Screenshots:**
App with navigation hint enabled. Works properly
![IMG_20240816_070359](https://github.com/user-attachments/assets/d5cbf6f4-0df6-4e98-a016-12be725600e9)

App with navigation hint disabled. Hold to stop not working:
![IMG_20240816_070342](https://github.com/user-attachments/assets/37cb34de-e2fd-45ad-9b36-a153f18887b9)

**Comment by dennisguse** [comment] 2024-08-16 09:21
Can you create a pull request for this?

My phone lacks that option to hide the gesture hint.

**Comment by dennisguse** [comment] 2024-09-08 09:47
Duplicate of #1893.

**Closed by dennisguse** 2024-09-08 09:47 UTC
Labels: bug, help wanted
