### ISSUE TITLE
Being able to export .gpx and .kmz into local files

### ISSUE THREAD

**Issue by xfarrow** [OpenTracksApp/OpenTracks#1337] opened 2022-07-25 19:46 UTC
**Is your feature request related to a problem? Please describe.**
Now we can either
1. Open another app and sending it a .gpx or .kmz file
2. Share a .kmz file to other people, but not saving it locally nor it is possible to share a .gpx file
3. Save locally ALL the tracks altogether

**Describe the solution you'd like**
I'd love if we could save locally a single .gpx or .kmz file. Ideally being able to share to people a .gpx file too

**Describe alternatives you've considered**
[empty]

**Additional context**
[empty]

**Comment by dennisguse** [comment] 2022-07-27 05:25
3. If you mean export all tracks into one file then this is a duplicate of #448.

2. I am confused about this. The share functionality is working. Is the problem that you can only select one format that is used for all exports?

1. Not really sure what you mean.

Your desired solution is a duplicate of #824.

**Closed** 2023-05-27 16:11 UTC
Labels: enhancement, PR welcome
