### ISSUE TITLE
Huge distance recorded, but all data look OK (OSM Dashboard tracks look good)

### ISSUE THREAD

**Issue by dhlocker** [OpenTracksApp/OpenTracks#1922] opened 2024-06-05 16:55 UTC
While recording tracks on an auto trip, five of the tracks recorded report huge final distances (22,586.56 mi; 11324.52 mi, 22687.96 mi; 11463.22 mi; and 12109.85 mi). I know that the 11463.22 record was correct at 48.04 mi; the actual final distance was about 56 miles.

This seems to be a random issue; seven other tracks recorded on the same trip had no problems. I am not able to reproduce the issue with any particular actions. All tracks were recorded by tapping the start button, then holding the start/stop button to stop. The phone was always in the same location in the vehicle during all tracks recording, or in my pocket while walking. In one case, I set three markers; in the other three cases, no markers were set; several other records with markers had no problem, so no consistency there.

Attached screenshots are from the first two instances, showing the Stats, [two] Intervals, By time, and By distance pages. Two Intervals pages are included - the "Early" one is where any discrepancy from reality is first noted and the "Late" one has the largest recorded distance. For the 11324 instance, I realised I could get more resolution in the Intervals distance so took another pair of Early and Late Intervals at 528ft intervals, which shows more precisely where the issue begins.

I could make the GPS coordinates available if that might help; I'm reluctant to export tracks because of potential storage issues.

Samsung Galaxy S22 (SM-S901U) H/W Rev 1.0
Android version 14; Kernel version 5.10.198-android12-9-28575149-abS901USQS5EXE2 #1 Fri May 10 18:49:30 UTC 2024
Opentracks v4.12.2; version code 5749

![Screenshot_OpenTracks-22586mi-Stats](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/2b1b4cff-c1dc-4f3a-bdda-8aea1bbbdd50)
![Screenshot_OpenTracks-22586mi-ByTime](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/0faead26-001a-457f-94b0-4f91bcdf00d7)
![Screenshot_OpenTracks-22586mi-ByDistance](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/e1be0095-1368-4124-bfc0-8e43a7ff6999)
![Screenshot_OpenTracks-22586mi-IntervalsEarly](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/19b26b17-b9a0-40eb-814c-5684506b2f7b)
![Screenshot_OpenTracks-22586mi-IntervalsLate](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/7a438bb5-4b21-4cb8-a088-b61d326c3299)
![Screenshot_OpenTracks-11324mi-Stats](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/7557a416-d8ea-4d4d-a6ca-b2d1125f1209)
![Screenshot_OpenTracks-11324mi-ByTime](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/7b74adf8-7456-4fbb-881b-fc384d29e68e)
![Screenshot_OpenTracks-11324mi-ByDistance](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/11b74e29-8c1b-4648-8b56-fe189a2e1664)
![Screenshot_OpenTracks-11324mi-IntervalsEarly](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/01bbf75b-07c5-49ae-a693-bbafd43e7782)
![Screenshot_OpenTracks-11324mi-IntervalsLate](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/e999eea9-a6cd-4fc6-8f94-1cf7e0b11fc3)
![Screenshot_OpenTracks-11324mi-IntervalHiResEarly](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/4716bdfa-a174-45e9-b301-1bc86da69c0e)
![Screenshot_OpenTracks-11324mi-IntervalHiResLate](https://github.com/OpenTracksApp/OpenTracks/assets/5805239/a18e854f-9332-4a75-bf5b-aec941a1bf6b)

**Comment by dennisguse** [comment] 2024-06-06 08:11
Duplicate of #1898.

Please upgrade to v4.12.3. 

Please note that the upgrade will not fix those tracks - it just prevents the occurrence of the problem. 
If you want to fix those tracks, you need to export them and remove the 0/0 coordinates.

**Closed** 2024-06-06 08:12 UTC
Labels: potential bug
