### ISSUE TITLE
Recording stops when minimizing OpenTracks or when pressing the power button to shut down the screen

### ISSUE THREAD

**Issue by pitkajuh** [OpenTracksApp/OpenTracks#1863] opened 2024-02-16 10:01 UTC
**Describe the bug**
Recording stops when minimizing OpenTracks or when pressing the power button to shut down the screen.

**To Reproduce**
1. Start recording
2. Minimize OpenTracks (go to home screen) or press the power button to shut down the screen
3. Recording stops

**Technical information**
 - Device: Google Pixel 6a
 - OS: GrapheneOS, UQ1A.240205.002.2024020500
 - OpenTracks version: 4.11.1, 5679

**Comment by dennisguse** [comment] 2024-02-16 16:25
Duplicate of #1853.
Please upgrade to v4.11.2 or downgrade to v4.11.0

**Closed by dennisguse** 2024-02-16 16:25 UTC
Labels: potential bug
